### ISSUE TITLE
[Bug] Test failure on several arches

### ISSUE THREAD

**Issue by werdahias** [libseccomp-rs/libseccomp-rs#265]
**Describe the bug**
libseccomp fails its testsuite on multiple arches

**Environment**

- libseccomp: e.g. `0.5.3`
- libseccomp-rs: 0.3.0
- Rust: e.g. output of `rustc -V` 1.70
- Architecture: s390x, i386, loongarch, ppc64
Logs:

loongarch:
```
test version::tests::test_ensure_supported_version ... ok
test api::tests::test_ensure_supported_api ... FAILED

failures:

---- api::tests::test_ensure_supported_api stdout ----
thread 'api::tests::test_ensure_supported_api' panicked at 'assertion failed: ensure_supported_api(\"test\", 3, ScmpVersion::from((2, 4, 0))).is_ok()', src/api.rs:133:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:117:5
   3: libseccomp::api::tests::test_ensure_supported_api
             at /usr/share/cargo/registry/libseccomp-0.3.0/src/api.rs:133:9
   4: libseccomp::api::tests::test_ensure_supported_api::{{closure}}
             at /usr/share/cargo/registry/libseccomp-0.3.0/src/api.rs:132:36
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    api::tests::test_ensure_supported_api

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

s390x:
```

test test_rule_add_exact_array_load ... ok

failures:

---- test_arch_functions stdout ----
thread 'test_arch_functions' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Errno(EDOM), source: None, message: "Architecture/ABI specific failure" }', tests/tests.rs:253:33
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.70.0/library/core/src/result.rs:1687:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.70.0/library/core/src/result.rs:1089:23
   4: tests::test_arch_functions
             at /usr/share/cargo/registry/libseccomp-0.3.0/tests/tests.rs:253:5
   5: tests::test_arch_functions::{{closure}}
             at /usr/share/cargo/registry/libseccomp-0.3.0/tests/tests.rs:251:26
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_merge_filters stdout ----
thread 'test_merge_filters' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Errno(EDOM), source: None, message: "Architecture/ABI specific failure" }', tests/tests.rs:273:37
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.70.0/library/core/src/result.rs:1687:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.70.0/library/core/src/result.rs:1089:23
   4: tests::test_merge_filters
             at /usr/share/cargo/registry/libseccomp-0.3.0/tests/tests.rs:273:5
   5: tests::test_merge_filters::{{closure}}
             at /usr/share/cargo/registry/libseccomp-0.3.0/tests/tests.rs:263:25
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_arch_functions
    test_merge_filters

test result: FAILED. 19 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```
ppc64:
```
test src/syscall.rs - syscall::ScmpSyscall::get_name (line 218) ... ok

failures:

---- src/filter_context.rs - filter_context::ScmpFilterContext::add_rule_conditional_exact (line 353) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Errno(EINVAL), source: None, message: "Invalid input to the libseccomp API" }', src/filter_context.rs:13:47
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.70.0/library/core/src/result.rs:1687:5
   3: core::result::Result<T,E>::unwrap
   4: rust_out::main
   5: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.



failures:
    src/filter_context.rs - filter_context::ScmpFilterContext::add_rule_conditional_exact (line 353)

```
i386:
```
test src/syscall.rs - syscall::ScmpSyscall::get_name (line 218) ... ok
test src/syscall.rs - syscall::ScmpSyscall::from_name_by_arch_rewrite (line 186) ... ok

failures:

---- src/filter_context.rs - filter_context::ScmpFilterContext::add_rule_conditional_exact (line 353) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Errno(EINVAL), source: None, message: "Invalid input to the libseccomp API" }', src/filter_context.rs:13:47
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.70.0/library/core/src/result.rs:1687:5
   3: core::result::Result<T,E>::unwrap
   4: rust_out::main
   5: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.



failures:
    src/filter_context.rs - filter_context::ScmpFilterContext::add_rule_conditional_exact (line 353)

test result: FAILED. 42 passed; 1 failed; 3 ignored; 0 measured; 0 filtered out; finished in 3.01s
```

**Comment by rusty-snake** [comment]
- loongarch: libseccomp 2.5.5 does not support loongarch
- ppc64, i386: Likely the same

**Comment by werdahias** [comment]
libseccomp build on s390x, i386, and ppc64 though: 
https://buildd.debian.org/status/package.php?p=libseccomp&suite=sid

I will skip those test on those arches then.

**Comment by rusty-snake** [comment]
Correct s390x, i386, and ppc64 are supported by libseccomp and Rust.
